apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-damage-detection-inference
  labels:
    app: car-damage-detection-inference
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: car-damage-detection-inference
  template:
    metadata:
      labels:
        app: car-damage-detection-inference
    spec:
      containers:
      - name: car-damage-detection-inference
        image: {{ .Values.inference.container.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
          - name: STEPS_PER_EPOCH
            value: {{ .Values.inference.env.steps }}

          - name: EPOCHS
            value: {{ .Values.inference.env.epochs }}

        ports:
        - containerPort: {{ .Values.inference.container.port }}
        
        resources:
          requests:
            cpu: "3500m"
            memory: "1500Mi"
          limits:
            cpu: "3500m"
            memory: "1500Mi"

        # volumeMounts:
        #   - name: logs-volume
        #     mountPath: "/logs"

      # volumes:
      #   - name: logs-volume
      #     persistentVolumeClaim:
      #       claimName: weights-volume
