apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: prometheus
  name: prometheus
  namespace: {{ .Values.namespace }}
spec: 
  endpoints:
  - interval: 30s
    targetPort: {{ .Values.inference.container.port }}
    path: /metrics
  namespaceSelector:
    matchNames:
    - dev
  selector:
    matchLabels:
      operated-prometheus: "true"