apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
      - name: car-damage-detection-training
        image: {{ .Values.training.container.image }}
        env:
          - name: STEPS_PER_EPOCH
            value: {{ .Values.training.env.steps }}
          - name: EPOCHS
            value: {{ .Values.training.env.epochs }}
        volumeMounts:
          - name: weights-volume
            mountPath: "/weights"

      restartPolicy: Never

      volumes:
        - name: weights-volume
          persistentVolumeClaim:
            claimName: weights-volume

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: worker-label
                operator: In
                values:
                - ai
      
      tolerations:
        - key: "worker-taint"
          operator: "Equal"
          value: "ai"
          effect: "NoSchedule"