apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress  # explicit deny on all pods in namespace
  namespace: car-damage-detection-develop
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-network-policy
  namespace: car-damage-detection-develop
spec:
  podSelector:
    matchLabels:
      app: car-damage-detection-training
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: car-damage-detection-inference
      ports:
        - protocol: TCP
          port: {{ .Values.inference.container.port }}