apiVersion: v1
kind: Service
metadata:
  name: car-damage-detection
  namespace: car-damage-detection-develop
spec:
  type: {{ .Values.infernce.service.type }}  
  selector:
    app: car-damage-detection
  ports:
    - protocol: TCP
      port: {{ .Values.inference.service.port }} 
      targetPort: {{ .Values.inference.container.port }}  