apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceMonitorSelector: prometheus
  name: prometheus
  namespace: car-damage-detection-develop
spec:
  endpoints:
  - interval: 30s
    targetPort: {{ .Values.inference.container.port }}
    path: /metrics
  namespaceSelector:
    matchNames:
    - car-damage-detection-develop
  selector:
    matchLabels:
      operated-prometheus: "true"