replicaCount: 1
imagePullPolicy: IfNotPresent
namespace: dev
Color: green

inference:
  container:
    image: bochrafeki/devops-project:inference
    port: 8000
  service:
    type: LoadBalancer
    port: 80
  env:
    steps: "100"
    epochs: "40"

training:
  container:
    image: bochrafeki/devops-project:training
  env:
    steps: "100"
    epochs: "40"